(cl:defpackage subt_msgs-srv
  (:use )
  (:export
   "POSEFROMARTIFACT"
   "<POSEFROMARTIFACT-REQUEST>"
   "POSEFROMARTIFACT-REQUEST"
   "<POSEFROMARTIFACT-RESPONSE>"
   "POSEFROMARTIFACT-RESPONSE"
  ))

